# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: ScanForSecrets
    dependsOn: []
    jobs:
      - job: GitSecrets
        steps:
        - script: mkdir $(build.artifactstagingdirectory)/git-secrets
          displayName: 'Create empty directory for git-secrets clone'

        - script: git clone https://github.com/awslabs/git-secrets $(build.artifactstagingdirectory)/git-secrets
          displayName: 'Clone git-secrets'

        - script: cd $(build.artifactstagingdirectory)/git-secrets; sudo make install;
          displayName: 'Make git-secrets install'

        - script: cd $(Build.Repository.LocalPath);git secrets --register-aws;git secrets --scan
          displayName: 'Scan pipeline repo for secrets'
  - stage: ContinueBuild
    dependsOn:
      - ScanForSecrets
    jobs:
      - job: NextJob
        steps:
        - script: echo 'Scan for secrets passed, continue.'
          displayName: 'Scan for secrets passed, continue'
